export const TABLE_HEIGHT = 'calc(100vh - 128px - 100px)'

export const DRAWER_WIDTH = 400

export const MARK_DATE_FORMAT = 'dd.MM'

export const LANGUAGES = {
  UK: 'uk',
  RU: 'ru',
  EN: 'en'
}

export const I18NEXT_RESOURCES = {
  [LANGUAGES.UK]: {
    translation: {
      usernameLabel: "Ім'я користувача",
      emailLabel: 'Електронна пошта',
      passwordLabel: 'Пароль',
      loginLabel: 'Увійти',
      timetableLabel: 'Розклад',
      studentsLabel: 'Студенти',
      subjectsLabel: 'Предмети',
      teachersLabel: 'Вчителі',
      chatLabel: 'Чат',
      firstNameLabel: "Ім'я",
      lastNameLabel: 'Прізвище',
      patronymicNameLabel: 'По батькові',
      instituteLabel: 'Інститут',
      departmentLabel: 'Кафедра',
      specialityLabel: 'Спецільність',
      groupLabel: 'Група',
      courseLabel: 'Курс',
      phoneLabel: 'Мобільний телефон',
      telegramLabel: 'Telegram',
      updateProfileLabel: 'Оновити профіль',
      editProfileLabel: 'Редагувати профиль',
      uploadImageLabel: 'Завантажити зображення',
      profileLabel: 'Профіль',
      tableSearchLabel: 'Пошук',
      emptyTableLabel: 'За пошуком нічого не знайдено',
      roomLabel: 'Аудиторія',
      laboratoryLabel: 'Лабораторна',
      lectureLabel: 'Лекція',
      weekViewLabel: 'На тиждень',
      monthViewLabel: 'На місяць',
      todayLabel: 'Сьогодні',
      studentLabel: 'Студент',
      subjectLabel: 'Предмет',
      subjectTypeLabel: 'Тип предмета',
      unreadMessages_0: 'У Вас {{count}} непрочитане повідомлення від {{user}}',
      unreadMessages_1:
        'У Вас {{count}} непрочитаних повідомлення від {{user}}',
      unreadMessages_2: 'У Вас {{count}} непрочитаних повідомлень від {{user}}',
      noUnreadMessagesLabel: 'Непрочитані повідомлення відстутні',
      invalidCredentialsLabel: 'Некоректні дані',
      requiredFieldLabel: "Обов'язкове поле",
      invalidEmailLabel: 'Некоректна електронна пошта'
    }
  },
  [LANGUAGES.RU]: {
    translation: {
      usernameLabel: 'Имя пользователя',
      emailLabel: 'Электронная почта',
      passwordLabel: 'Пароль',
      loginLabel: 'Войти',
      timetableLabel: 'Расписание',
      studentsLabel: 'Студенты',
      subjectsLabel: 'Предметы',
      teachersLabel: 'Преподаватели',
      chatLabel: 'Чат',
      firstNameLabel: 'Имя',
      lastNameLabel: 'Фамилия',
      patronymicNameLabel: 'Отчество',
      instituteLabel: 'Институт',
      departmentLabel: 'Кафедра',
      specialityLabel: 'Специальность',
      groupLabel: 'Группа',
      courseLabel: 'Курс',
      phoneLabel: 'Мобильный телефон',
      telegramLabel: 'Telegram',
      updateProfileLabel: 'Обновить профиль',
      editProfileLabel: 'Редактировать профиль',
      uploadImageLabel: 'Загрузить изображение',
      profileLabel: 'Профиль',
      tableSearchLabel: 'Поиск',
      emptyTableLabel: 'По поиску ничего не найдено',
      roomLabel: 'Аудитория',
      laboratoryLabel: 'Лабораторная',
      lectureLabel: 'Лекция',
      weekViewLabel: 'На неделю',
      monthViewLabel: 'На месяц',
      todayLabel: 'Сегодня',
      studentLabel: 'Студент',
      subjectLabel: 'Предмет',
      subjectTypeLabel: 'Тип предмета',
      unreadMessages_0: 'У Вас {{count}} непрочитанное сообщение от {{user}}',
      unreadMessages_1: 'У Вас {{count}} непрочитанных сообщения от {{user}}',
      unreadMessages_2: 'У Вас {{count}} непрочитанных сообщений от {{user}}',
      noUnreadMessagesLabel: 'Непрочитанные сообщения отсутствуют',
      invalidCredentialsLabel: 'Некорректные данные',
      requiredFieldLabel: 'Обязательное поле',
      invalidEmailLabel: 'Некорректная электронная почта'
    }
  },
  [LANGUAGES.EN]: {
    translation: {
      usernameLabel: 'Username',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      loginLabel: 'Login',
      timetableLabel: 'Timetable',
      studentsLabel: 'Students',
      subjectsLabel: 'Subjects',
      teachersLabel: 'Teachers',
      chatLabel: 'Chat',
      firstNameLabel: 'First name',
      lastNameLabel: 'Last name',
      patronymicNameLabel: 'Patronymic name',
      instituteLabel: 'Institute',
      departmentLabel: 'Department',
      specialityLabel: 'Speciality',
      groupLabel: 'Group',
      courseLabel: 'Course',
      phoneLabel: 'Phone number',
      telegramLabel: 'Telegram',
      updateProfileLabel: 'Update profile',
      editProfileLabel: 'Edit profile',
      uploadImageLabel: 'Upload image',
      profileLabel: 'Profile',
      tableSearchLabel: 'Search',
      emptyTableLabel: 'No results based on search',
      roomLabel: 'Room',
      laboratoryLabel: 'Laboratory',
      lectureLabel: 'Lecture',
      weekViewLabel: 'Week',
      monthViewLabel: 'Month',
      todayLabel: 'Today',
      studentLabel: 'Student',
      subjectLabel: 'Subject',
      subjectTypeLabel: 'Subject type',
      unreadMessages: 'You have {{count}} unread message from {{user}}',
      unreadMessages_plural: 'You have {{count}} messages from {{user}}',
      noUnreadMessagesLabel: 'Unread messages not found',
      invalidCredentialsLabel: 'Invalid credentials',
      requiredFieldLabel: 'Required field',
      invalidEmailLabel: 'Invalid email'
    }
  }
}
